version: '3.2'

services:
  gameserver:
    image: roboruckus/game-server:latest
    container_name: roboruckus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ARGS=--options=botless  # Set launch arguments here, e.g. --options=botless
    volumes:
      - ./Ruckus/Boards:/app/GameConfig/Boards
      - ./Ruckus/Images:/app/wwwroot/images/boards
    ports:
      - 8082:8082
    restart: unless-stopped # Set the server to auto-strat and auto-restart

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    #container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
    volumes:
      - ~/Projects:/config
    ports:
      - 8443:8443
    restart: unless-stopped